# Generated by Django 3.2.25 on 2026-07-17 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='停用原因')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='预计结束时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('ongoing', '进行中'), ('completed', '已完成'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='venues.room', verbose_name='场地')),
            ],
            options={
                'verbose_name': '维修停用',
                'verbose_name_plural': '维修停用',
                'db_table': 'maintenance_maintenance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['venue'], name='idx_maintenance_venue'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['status'], name='idx_maintenance_status'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['start_time', 'end_time'], name='idx_maintenance_time'),
        ),
    ]
