# Generated by Django 3.2.25 on 2026-07-17 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='预约编号')),
                ('title', models.CharField(max_length=200, verbose_name='使用目的')),
                ('booking_type', models.CharField(choices=[('teaching', '教学'), ('meeting', '会议'), ('activity', '活动'), ('self_study', '自习')], default='meeting', max_length=20, verbose_name='预约用途')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='结束时间')),
                ('participant_count', models.IntegerField(verbose_name='参与人数')),
                ('required_equipments', models.JSONField(blank=True, default=list, help_text='设备ID列表', verbose_name='所需设备')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('completed', '已完成')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.IntegerField(default=0, help_text='教师=1，学生=0', verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.room', verbose_name='场地')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'db_table': 'bookings_booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['venue', 'start_time', 'end_time'], name='idx_booking_time'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='idx_booking_user'),
        ),
    ]
