# Generated by Django 3.2.25 on 2026-07-19 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_auto_20260718_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('notification_type', models.CharField(choices=[('system', '系统消息'), ('booking', '预约消息'), ('approval', '审批消息'), ('reminder', '提醒消息')], default='system', max_length=20, verbose_name='消息类型')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='相关链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '站内消息',
                'verbose_name_plural': '站内消息',
                'db_table': 'bookings_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='idx_notification_user_read'),
        ),
    ]
