# Generated by Django 3.2.25 on 2026-07-17 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='楼宇名称')),
                ('location', models.CharField(blank=True, help_text='楼宇的具体位置描述', max_length=200, null=True, verbose_name='位置')),
                ('total_floors', models.IntegerField(default=1, verbose_name='总楼层数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '楼宇',
                'verbose_name_plural': '楼宇',
                'db_table': 'venues_building',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='设备名称')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='设备编码')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'venues_equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='场地名称')),
                ('venue_type', models.CharField(choices=[('classroom', '教室'), ('meeting_room', '会议室'), ('lab', '实验室'), ('activity_room', '活动室')], default='classroom', max_length=50, verbose_name='场地类型')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='楼层')),
                ('room_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='房间号')),
                ('capacity', models.IntegerField(help_text='场地可容纳的最大人数', verbose_name='容纳人数')),
                ('area', models.DecimalField(blank=True, decimal_places=2, help_text='单位：平方米', max_digits=10, null=True, verbose_name='面积')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='负责人')),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='负责人电话')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('available', '可用'), ('maintenance', '维修中'), ('disabled', '已停用')], default='available', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='venues.building', verbose_name='所属楼宇')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '场地',
                'verbose_name_plural': '场地',
                'db_table': 'venues_room',
                'ordering': ['building__name', 'floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('status', models.CharField(choices=[('normal', '正常'), ('broken', '已损坏'), ('maintenance', '维修中')], default='normal', max_length=20, verbose_name='状态')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='最后维护日期')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_equipments', to='venues.equipment', verbose_name='设备')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_equipments', to='venues.room', verbose_name='场地')),
            ],
            options={
                'verbose_name': '场地设备',
                'verbose_name_plural': '场地设备',
                'db_table': 'venues_room_equipment',
                'unique_together': {('room', 'equipment')},
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='idx_room_name'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['venue_type'], name='idx_room_type'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building'], name='idx_room_building'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='idx_room_status'),
        ),
    ]
