# Generated by Django 3.2.25 on 2026-07-17 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('teacher', models.CharField(blank=True, max_length=100, null=True, verbose_name='授课教师')),
                ('day_of_week', models.IntegerField(help_text='1-7，周一到周日', verbose_name='周几')),
                ('period', models.CharField(help_text='如：1-2, 3-4, 5-6等', max_length=20, verbose_name='节次')),
                ('start_week', models.IntegerField(verbose_name='开始周次')),
                ('end_week', models.IntegerField(verbose_name='结束周次')),
                ('class_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='班级')),
                ('student_count', models.IntegerField(blank=True, null=True, verbose_name='学生人数')),
                ('semester', models.CharField(help_text='如：2025-2026-2', max_length=50, verbose_name='学期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='venues.room', verbose_name='场地')),
            ],
            options={
                'verbose_name': '固定课表',
                'verbose_name_plural': '固定课表',
                'db_table': 'schedules_schedule',
                'ordering': ['semester', 'day_of_week', 'period'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['venue'], name='idx_schedule_venue'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['semester'], name='idx_schedule_semester'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['day_of_week'], name='idx_schedule_day'),
        ),
    ]
